<?xml version="1.0" ?>
<project name="jsalem" default="jar">
  <property name="src" value="." />
  <property name="build" value="build" />
  <property name="classes" value="${build}/classes" />
  <property name="lib" value="lib" />
  <target name="build-env">
    <mkdir dir="${build}" />
    <mkdir dir="${classes}" />
  </target>
  <target name="compile" depends="build-env">
    <javac srcdir="${src}" destdir="${classes}" debug="on" source="11" target="11" includeantruntime="no" encoding="iso-8859-1">
      <classpath>
        <pathelement path="${lib}/jogl.jar" />
        <pathelement path="${lib}/gluegen-rt.jar" />
      </classpath>
      <compilerarg value="-Xlint:unchecked" />
    </javac>
    <copy todir="${classes}">
      <fileset dir="${src}" excludes="**/*.java,build.xml" />
    </copy>
  </target>
  <target name="jar" depends="compile">
    <jar destfile="${build}/jsalem.jar">
      <fileset dir="${classes}" />
      <manifest>
        <attribute name="Main-Class" value="haven.MainFrame" />
        <attribute name="Class-Path" value="jogl.jar gluegen-rt.jar steamworks4j.jar builtin-res.jar salem-res.jar" />
        <attribute name="Permissions" value="all-permissions" />
        <attribute name="Codebase" value="*" />
        <attribute name="Application-Name" value="jsalem" />
      </manifest>
    </jar>
  </target>
  <target name="run" depends="jar">
    <java jar="${build}/jsalem.jar" dir="${build}" fork="true" maxmemory="1024m">
      <arg line="-U http://game.salemthegame.com/res/ game.salemthegame.com"/>
    </java>
  </target>
  <target name="clean">
    <delete dir="${build}" />
  </target>
</project>
